# Generated by Django 6.0.1 on 2026-01-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDB',
            fields=[
                ('Order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Restaurant', models.CharField()),
                ('Amount', models.IntegerField()),
                ('Items', models.CharField()),
                ('Mobile_no', models.IntegerField()),
            ],
        ),
    ]
